#!C:/Program\ Files/Git/bin/sh.exe

###
# set these environment variables first (as system variables, not user variables):
#  DRUPAL_ENV <- dev
#  DEV_TARGET <- //awsd76.main.dva/DVAInternet2018/sites/all/themes/custom/dva
#
#
# ... then copy this file into .git/hooks
#
# now every time you commit to the repository, git will automatically copy the latest files 
# on to the dev server (currently only css, js and template files are copied)
#

# check environment variables 
echo  "Commit detected - activating deploy script..." > output.txt
echo  "Environment = $DRUPAL_ENV, target = $DEV_TARGET" >> output.txt
echo  "...." >> output.txt


# check commit/tag details
if [ "$DRUPAL_ENV" = "dev" ]
then 
  cp -r -u css $DEV_TARGET 2>> output.txt
  cp -r -u js $DEV_TARGET 2>> output.txt
  cp -r -u templates $DEV_TARGET 2>> output.txt
  
  echo  " ... copied new css, js and template files to $DEV_TARGET" >> output.txt
fi